import json
import time
from datetime import datetime
from typing import Optional


REPORT_TEMPLATES = {
    "executive": {
        "name": "Executive Summary",
        "description": "High-level report for management — risk overview, business impact, key recommendations",
        "sections": ["Executive Summary", "Risk Rating", "Key Findings", "Business Impact", "Recommendations", "Next Steps"],
    },
    "technical": {
        "name": "Technical Report",
        "description": "Detailed technical findings with full PoC, tool output, and remediation",
        "sections": ["Scope", "Methodology", "Tools Used", "Findings", "Proof of Concept", "Remediation", "Appendix"],
    },
    "compliance": {
        "name": "Compliance Report",
        "description": "Framework-mapped findings for audit (OWASP, NIST, PCI-DSS, ISO 27001)",
        "sections": ["Scope", "Framework Mapping", "Control Assessment", "Findings by Control", "Gap Analysis", "Remediation Timeline"],
    },
    "bug-bounty": {
        "name": "Bug Bounty Report",
        "description": "HackerOne/Bugcrowd-style vulnerability report",
        "sections": ["Title", "Severity", "Description", "Steps to Reproduce", "Impact", "Proof of Concept", "Remediation"],
    },
    "debrief": {
        "name": "Engagement Debrief",
        "description": "Quick debrief summary of a pentest session",
        "sections": ["Engagement Overview", "Timeline", "Findings Summary", "Attack Paths", "Recommendations"],
    },
}


class ReportGenerator:
    def __init__(self):
        self.templates = dict(REPORT_TEMPLATES)

    def list_templates(self) -> list[dict]:
        return [{"key": k, "name": v["name"], "description": v["description"]} for k, v in self.templates.items()]

    def generate(self, template_key: str, messages: list[dict], metadata: dict = None) -> str:
        template = self.templates.get(template_key)
        if not template:
            return f"Unknown template: {template_key}"

        meta = metadata or {}
        lines = []
        lines.append(f"# {template['name']}")
        lines.append(f"\n**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        if meta.get("target"):
            lines.append(f"**Target:** {meta['target']}")
        if meta.get("tester"):
            lines.append(f"**Tester:** {meta['tester']}")
        lines.append(f"**Model:** {meta.get('model', 'N/A')}")
        lines.append(f"**Provider:** {meta.get('provider', 'N/A')}")
        lines.append("")

        findings = self._extract_findings(messages)
        tools_used = self._extract_tools(messages)

        for section in template["sections"]:
            lines.append(f"\n## {section}\n")
            if section == "Executive Summary":
                lines.append(f"This assessment identified **{len(findings)}** finding(s) during the engagement.")
                lines.append(f"Tools and techniques used: {', '.join(tools_used[:10]) if tools_used else 'N/A'}")
            elif section in ("Findings", "Key Findings", "Findings by Control", "Findings Summary"):
                if findings:
                    for i, f in enumerate(findings, 1):
                        lines.append(f"### Finding {i}")
                        lines.append(f"{f[:500]}")
                        lines.append("")
                else:
                    lines.append("No significant findings recorded in this session.")
            elif section == "Tools Used":
                if tools_used:
                    for t in sorted(set(tools_used)):
                        lines.append(f"- {t}")
                else:
                    lines.append("- Manual testing")
            elif section == "Steps to Reproduce":
                user_msgs = [m for m in messages if m.get("role") == "user"]
                for i, m in enumerate(user_msgs[:10], 1):
                    content = m.get("content", "")
                    if isinstance(content, str) and content.strip():
                        lines.append(f"{i}. {content[:200]}")
            elif section == "Timeline":
                lines.append("| Time | Action |")
                lines.append("|------|--------|")
                for m in messages[:20]:
                    role = m.get("role", "")
                    content = str(m.get("content", ""))[:80]
                    if role in ("user", "assistant"):
                        lines.append(f"| {role} | {content} |")
            else:
                lines.append("*[To be completed by the assessor]*")

        lines.append(f"\n---\n*Generated by ZER0CODE*")
        return "\n".join(lines)

    def _extract_findings(self, messages: list[dict]) -> list[str]:
        findings = []
        keywords = ["vulnerability", "found", "discovered", "critical", "high", "medium", "exploit", "injection", "xss", "sqli", "ssrf", "rce", "idor", "bypass"]
        for m in messages:
            if m.get("role") != "assistant":
                continue
            content = str(m.get("content", ""))
            if any(kw in content.lower() for kw in keywords):
                for para in content.split("\n\n"):
                    if any(kw in para.lower() for kw in keywords) and len(para) > 50:
                        findings.append(para.strip())
        return findings[:20]

    def _extract_tools(self, messages: list[dict]) -> list[str]:
        tools = []
        for m in messages:
            if m.get("role") == "tool":
                name = m.get("name", "")
                if name:
                    tools.append(name)
        return tools
