import json
from datetime import datetime
from pathlib import Path


class SessionExporter:
    def __init__(self):
        self._styles = {
            "user": "**You:**",
            "assistant": "**TRUTHZERO:**",
            "system": "*[System]*",
            "tool": "**Tool Result:**",
        }

    def to_markdown(self, messages: list[dict], metadata: dict = None) -> str:
        lines = []
        lines.append("# TRUTHZERO Session Report")
        lines.append(f"\n**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if metadata:
            if metadata.get("provider"):
                lines.append(f"**Provider:** {metadata['provider']}")
            if metadata.get("model"):
                lines.append(f"**Model:** {metadata['model']}")
            if metadata.get("total_tokens"):
                lines.append(f"**Tokens Used:** {metadata['total_tokens']:,}")
            if metadata.get("total_cost"):
                lines.append(f"**Total Cost:** {metadata['total_cost']}")
            if metadata.get("session_id"):
                lines.append(f"**Session ID:** {metadata['session_id']}")
        lines.append("\n---\n")

        for msg in messages:
            role = msg.get("role", "unknown")
            content = msg.get("content", "")

            if role == "system" and "CONVERSATION SUMMARY" in str(content):
                continue
            if role == "system" and "LOADED SKILL" not in str(content):
                continue

            if not isinstance(content, str):
                content = json.dumps(content, indent=2)

            prefix = self._styles.get(role, f"**{role}:**")

            if role == "tool":
                name = msg.get("name", "unknown")
                lines.append(f"\n> **Tool: {name}**")
                if len(content) > 500:
                    content = content[:500] + "\n... (truncated)"
                lines.append(f"```\n{content}\n```\n")
            elif role == "assistant" and msg.get("tool_calls"):
                if content:
                    lines.append(f"\n{prefix}\n{content}\n")
                for tc in msg.get("tool_calls", []):
                    name = tc.get("name", "unknown")
                    args = tc.get("arguments", "{}")
                    if isinstance(args, str):
                        try:
                            args = json.dumps(json.loads(args), indent=2)
                        except Exception:
                            pass
                    lines.append(f"\n> **Calling tool: {name}**")
                    lines.append(f"```json\n{args}\n```\n")
            else:
                if content.strip():
                    lines.append(f"\n{prefix}\n{content}\n")

        lines.append("\n---\n")
        lines.append("*Report generated by TRUTHZERO v0.2.0*\n")
        return "\n".join(lines)

    def to_html(self, messages: list[dict], metadata: dict = None) -> str:
        md_content = self.to_markdown(messages, metadata)
        html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>TRUTHZERO Session Report</title>
<style>
body {{ font-family: 'Fira Code', 'Consolas', monospace; background: #0a0a0a; color: #00ff41; max-width: 900px; margin: 0 auto; padding: 2em; }}
h1 {{ color: #00ff41; border-bottom: 2px solid #00ff41; }}
blockquote {{ border-left: 3px solid #00ff41; padding-left: 1em; color: #888; }}
pre {{ background: #111; padding: 1em; border-radius: 4px; overflow-x: auto; border: 1px solid #333; }}
code {{ color: #00ff41; }}
strong {{ color: #0ff; }}
hr {{ border: 1px solid #333; }}
</style></head><body>
{self._md_to_html(md_content)}
</body></html>"""
        return html

    def _md_to_html(self, md: str) -> str:
        import re
        html = md
        html = re.sub(r'^# (.+)$', r'<h1>\1</h1>', html, flags=re.MULTILINE)
        html = re.sub(r'^## (.+)$', r'<h2>\1</h2>', html, flags=re.MULTILINE)
        html = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', html)
        html = re.sub(r'\*(.+?)\*', r'<em>\1</em>', html)
        html = re.sub(r'```(\w+)?\n(.*?)```', r'<pre><code>\2</code></pre>', html, flags=re.DOTALL)
        html = re.sub(r'^> (.+)$', r'<blockquote>\1</blockquote>', html, flags=re.MULTILINE)
        html = re.sub(r'^---$', r'<hr>', html, flags=re.MULTILINE)
        html = html.replace('\n', '<br>\n')
        return html

    def save(self, messages: list[dict], filepath: str, format: str = "md", metadata: dict = None) -> str:
        path = Path(filepath).expanduser().resolve()
        path.parent.mkdir(parents=True, exist_ok=True)
        if format == "html":
            content = self.to_html(messages, metadata)
        else:
            content = self.to_markdown(messages, metadata)
        path.write_text(content, encoding="utf-8")
        return str(path)
